# Default values for hugo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: hugo
replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: Always


service:
  type: LoadBalancer
  port: 80
